FROM python:3

# STEP4-4では以下は変更しない
################## BEGIN INSTALLATION ######################

#  define the working directory and copy folder from Local machine
WORKDIR /app
COPY db/ ./db
COPY python/ ./python

# (3. Install dependencies)
WORKDIR /app/python
RUN pip3 install -r requirements.txt

##################### INSTALLATION END #####################

# executing the command (4. Run the Python app)
CMD [ "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "9000"]
